#!/bin/sh

if [ -f /data/mysql.configured ]; then
  exit 0
fi

#
# create all directories if missing
#
mkdir -p /data/conf
mkdir -p /data/log/mysql
mkdir -p /data/db/mysql/
mkdir -p /var/run/mysqld


#
# set correct owner
#
chmod -R 777 /data
chown -R mysql.mysql /data
chown -R mysql.mysql /data/log/mysql 
chown -R mysql.mysql /data/db/mysql
chown -R mysql.mysql /var/run/mysqld

#
# check for config-file
#

if [ ! -f /data/conf/my.cnf ]; then
  cp /etc/mysql/my.cnf  /data/conf/my.cnf
  chmod +r /data/conf/my.cnf  
fi

# determine root password
unset ROOT_PASSWORD

if [ -z "$MARIADB_ROOT_PASSWORD" ]; then
  ROOT_PASSWORD=`date +%s | sha256sum | base64 | head -c 16 ; echo`
  echo "set root to random password $ROOT_PASSWORD"
else
  ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    echo "seting root password to ROOT_PASSWORD"
fi

if [ -z "$ROOT_PASSWORD" ]; then
     echo "ERROR: No root password defined"
     exit 1
fi

if [ ! -d /data/db/mysql/mysql ]; then
  # initialize database if not found
  /usr/bin/mysql_install_db --datadir=/data/db/mysql/ --user=mysql 2> /dev/null

  # start database for config

  /usr/bin/mysqld_safe --defaults-file=/data/conf/my.cnf --datadir=/data/db/mysql/  &

  # wait for it to start
  echo -n "wait for db to start"     

  c=1
  while [[ $c -le 10 ]]
  do
    echo 'SELECT 1' | /usr/bin/mysql &> /dev/null
#    echo "R=$?"
    if [ $? -eq 0 ]; then
      break 
    fi
    echo "."
    sleep 1
    let c=c+1
  done
  echo "C=$c"

  if [ $c -eq 11 ]; then
    echo "database failed to start"
    exit 1
  fi

  # remove some stuff

  echo "DROP DATABASE IF EXISTS test;" | /usr/bin/mysql 
  echo "DELETE FROM mysql.user WHERE user='';" | /usr/bin/mysql

  if [ ! -z $MARIADB_DATABASE ]; then                                                                                                
     echo "Creating database $MARIADB_DATABASE"                                                                                      
     echo "CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE ;" | /usr/bin/mysql                                        
  fi     

  if [ ! -z $MARIADB_USER ]; then
     echo "Creating user $MARIADB_USER"
     echo "CREATE USER '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_USER_PASSWORD' ;FLUSH PRIVILEGES;" | /usr/bin/mysql
     echo "CREATE USER '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_USER_PASSWORD' ;FLUSH PRIVILEGES;" | /usr/bin/mysql
     if [ ! -z $MARIADB_DATABASE ]; then 
       echo "Grating access for $MARIADB_USER to $MARIADB_DATABASE"
       echo "GRANT ALL ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%' ;FLUSH PRIVILEGES;" | /usr/bin/mysql 
       echo "GRANT ALL ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'localhost' ;FLUSH PRIVILEGES;" | /usr/bin/mysql 
     fi
  fi

  if [ ! -z "$MARIADB_REMOTE_ROOT" ]; then
    VAL=$(echo "$MARIADB_REMOTE_ROOT" | awk '{print toupper($0)}')
    if [[ $VAL = YES ]]; then
      echo "Grant root access from remote host"
      echo "GRANT ALL ON *.* to 'root'@'%' IDENTIFIED BY '$ROOT_PASSWORD' ;" | /usr/bin/mysql
    fi
  fi

  if [ ! -z "$ROOT_PASSWORD" ]; then
     echo "UPDATE mysql.user SET Password=PASSWORD('$ROOT_PASSWORD') WHERE User='root';FLUSH PRIVILEGES;" | /usr/bin/mysql
     echo "root password updated"
  fi 

fi

# finished, stop it an runit start the mysqld

/usr/bin/mysqladmin shutdown -p"$MARIADB_ROOT_PASSWORD"

# mark configured

touch /data/mysql.configured

